### ISSUE TITLE
unable to update file when editing existing flow function

### ISSUE THREAD

**Issue by ghost** [second-state/reactor-wasm#29]
as indicated in the screenshot, no "update file" button shows on UI

![image](https://user-images.githubusercontent.com/39196302/189448457-9c78b792-ced2-460f-ba5a-eaac7eda181f.png)

**Comment by ho-229** [comment]
Please turn off the flow first :)

**Comment by ghost** [comment]
it works, thanks!

**Comment by alabulei1** [comment]
We should add an alert when users check out the running flows. It could be Your flow is running now. To edit, please turn off the flow first.

**Comment by alabulei1** [comment]
@JYC0413  Please check out this issue.

**Comment by ho-229** [comment]
Now can specify the repo and path to build wasm file instead of upload it manually.
